# Generated by Django 6.0.3 on 2026-03-31 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Año'),
        ),
    ]
